mount: handle symlinks and improve updating systemplate
We should have no symlinks in the jail whatsoever, except
those we create to files known to exist in the jail.

Unfortunately, some systems have some of the /etc files
as symlinks. When we create hard-links to these files,
they can't be accessed from the jail, since the path
they point to isn't replicated in systemplate and jails.

First change here is to always link to the source file or,
when copying, to copy the source rather than a symlink.

Next, to detect modifications, we compare not just the
size and timestamp, but also the contents. This way we
can be certain that any modification will be detected.

Finally, when we copy at least one file in the
systemplate/etc directory, we flag it by creating the
'copied' file. This way we have a reliable indicator
and don't need to second guess if the files are
hard-linked or copied.

We also avoid some noisy errors when we fail to update
systemplate when it's read-only by first checking
if systemplate is writable or not and insue a friendly
log instead.

Change-Id: Ie8c3e70ea4ec19ee098309f8666c00639fa7319b

diff --git a/loolwsd-systemplate-setup b/loolwsd-systemplate-setup
--- a/loolwsd-systemplate-setup
+++ b/loolwsd-systemplate-setup
@@ -1,5 +1,5 @@
 #!/bin/bash
-#set -x
+# set -x
 
 test $# -eq 2 || { echo "Usage: $0 <chroot template directory for system libs to create> <LO installation directory>"; exit 1; }
 
@@ -66,11 +66,14 @@ grep -v dynamic | cut -d " " -f 3 | grep -E '^(/lib|/usr)' | sort -u | sed -e 's
 cpio -p -d -L $CHROOT
 
 # Link the dynamic files, replacing any existing.
+rm -f $CHROOT/etc/copied
 for file in hosts nsswitch.conf resolv.conf passwd group host.conf timezone localtime
 do
-    #echo "Linking/Copying /etc/$file"
+    # echo "Linking/Copying /etc/$file"
     # Prefer hard-linking, fallback to just copying (do *not* use soft-linking because that would be relative to the jail).
-    ln -f /etc/$file $CHROOT/etc/ 2> /dev/null || cp /etc/$file $CHROOT/etc/ || echo "Failed to link or copy $file"
+    # When copying, we must make sure that we copy the source and not a symlink. Otherwise, the source won't be accessible from the jail.
+    # In addition, we flag that at least one file is copied by creating the 'copied' file, so that we do check for updates.
+    ln -f `realpath /etc/$file` $CHROOT/etc/$file || (cp --dereference --preserve=all /etc/$file $CHROOT/etc/$file && touch $CHROOT/etc/copied) || echo "Failed to link or copy $file"
 done
 
 # Link dev/random and dev/urandom to ../tmp/dev/.
