loleaflet: makefile: change vars LOLEAFLET -> COOL
Change-Id: Ia65ca110659746d77404720022f56cae2cef5c6f
Signed-off-by: Henry Castro <hcastro@collabora.com>

diff --git a/loleaflet/Makefile.am b/loleaflet/Makefile.am
--- a/loleaflet/Makefile.am
+++ b/loleaflet/Makefile.am
@@ -42,24 +42,24 @@ JQUERY_MINIFIED_IMAGE_PATH = node_modules/jquery-ui-dist/images
 JQUERY_MINIFIED_IMAGES = $(wildcard $(JQUERY_MINIFIED_IMAGE_PATH)/*.png)
 JQUERY_MINIFIED_DIST_IMAGES = $(patsubst $(JQUERY_MINIFIED_IMAGE_PATH)/%.png,$(DIST_FOLDER)/images/%.png,$(JQUERY_MINIFIED_IMAGES))
 
-LOLEAFLET_IMAGES_SRC = $(shell find $(srcdir)/images -name '*.*')
-LOLEAFLET_IMAGES_DST = $(patsubst $(srcdir)/%,$(DIST_FOLDER)/%,$(LOLEAFLET_IMAGES_SRC))
-LOLEAFLET_IMAGES_CUSTOM_SRC = $(shell if test -n "$(CUSTOM_ICONS_DIRECTORY)"; then find $(CUSTOM_ICONS_DIRECTORY) -name '*.*'; fi)
-LOLEAFLET_IMAGES_CUSTOM_DST = $(patsubst $(CUSTOM_ICONS_DIRECTORY)/%,$(DIST_FOLDER)/images/%,$(LOLEAFLET_IMAGES_CUSTOM_SRC))
-LOLEAFLET_L10N_SRC = $(shell find $(srcdir)/l10n -name '*.*')
+COOL_IMAGES_SRC = $(shell find $(srcdir)/images -name '*.*')
+COOL_IMAGES_DST = $(patsubst $(srcdir)/%,$(DIST_FOLDER)/%,$(COOL_IMAGES_SRC))
+COOL_IMAGES_CUSTOM_SRC = $(shell if test -n "$(CUSTOM_ICONS_DIRECTORY)"; then find $(CUSTOM_ICONS_DIRECTORY) -name '*.*'; fi)
+COOL_IMAGES_CUSTOM_DST = $(patsubst $(CUSTOM_ICONS_DIRECTORY)/%,$(DIST_FOLDER)/images/%,$(COOL_IMAGES_CUSTOM_SRC))
+COOL_L10N_SRC = $(shell find $(srcdir)/l10n -name '*.*')
 if !ENABLE_MOBILEAPP
-LOLEAFLET_L10N_DST =  $(patsubst $(srcdir)/l10n/%,$(DIST_FOLDER)/l10n/%,$(LOLEAFLET_L10N_SRC))
+COOL_L10N_DST =  $(patsubst $(srcdir)/l10n/%,$(DIST_FOLDER)/l10n/%,$(COOL_L10N_SRC))
 endif
 
-LOLEAFLET_HTML_SRC = $(shell find $(srcdir)/html -name '*.html')
-LOLEAFLET_HTML_DST = $(patsubst $(srcdir)/html/%.html,$(DIST_FOLDER)/%.html,$(LOLEAFLET_HTML_SRC))
+COOL_HTML_SRC = $(shell find $(srcdir)/html -name '*.html')
+COOL_HTML_DST = $(patsubst $(srcdir)/html/%.html,$(DIST_FOLDER)/%.html,$(COOL_HTML_SRC))
 
-LOLEAFLET_WELCOME_SRC = $(shell find $(srcdir)/welcome -name '*.html')
-LOLEAFLET_WELCOME_DST = $(patsubst $(srcdir)/welcome/%.html,$(DIST_FOLDER)/welcome/%.html,$(LOLEAFLET_WELCOME_SRC))
+COOL_WELCOME_SRC = $(shell find $(srcdir)/welcome -name '*.html')
+COOL_WELCOME_DST = $(patsubst $(srcdir)/welcome/%.html,$(DIST_FOLDER)/welcome/%.html,$(COOL_WELCOME_SRC))
 
-LOLEAFLET_ADMIN_SRC = $(shell find $(srcdir)/admin -name '*.html' -or -name '*.css' -or -name '*.ttf' -or -name 'OFL.txt' -or -name '*.svg')
-LOLEAFLET_ADMIN_ALL = $(shell find $(srcdir)/admin -name '*')
-LOLEAFLET_ADMIN_DST = $(patsubst $(srcdir)/admin/%,$(DIST_FOLDER)/admin/%,$(LOLEAFLET_ADMIN_SRC))
+COOL_ADMIN_SRC = $(shell find $(srcdir)/admin -name '*.html' -or -name '*.css' -or -name '*.ttf' -or -name 'OFL.txt' -or -name '*.svg')
+COOL_ADMIN_ALL = $(shell find $(srcdir)/admin -name '*')
+COOL_ADMIN_DST = $(patsubst $(srcdir)/admin/%,$(DIST_FOLDER)/admin/%,$(COOL_ADMIN_SRC))
 
 define file_target
 $(1): $(2)
@@ -89,12 +89,12 @@ define npm_source
 	done
 endef
 
-LOLEAFLET_ADMIN_TS =\
+COOL_ADMIN_TS =\
 	admin/src/ModalDialogCreator.ts
 
-LOLEAFLET_ADMIN_TS_JS = $(patsubst %.ts,$(TYPESCRIPT_JS_DIR)/%.js,$(LOLEAFLET_ADMIN_TS))
+COOL_ADMIN_TS_JS = $(patsubst %.ts,$(TYPESCRIPT_JS_DIR)/%.js,$(COOL_ADMIN_TS))
 
-LOLEAFLET_ADMIN_JS =\
+COOL_ADMIN_JS =\
 	admin/src/Base.js \
 	admin/src/Admin.js \
 	admin/src/AdminSocketBase.js \
@@ -113,7 +113,7 @@ NODE_MODULES_SRC =\
 	l10n-for-node@0.0.1 \
 	@braintree/sanitize-url@4.0.1
 
-LOLEAFLET_CSS_LST =\
+COOL_CSS_LST =\
 	$(builddir)/node_modules/select2/dist/css/select2.css \
 	$(srcdir)/css/w2ui-1.5.rc1.css \
 	$(srcdir)/css/leaflet.css \
@@ -146,15 +146,15 @@ LOLEAFLET_CSS_LST =\
 	$(srcdir)/css/jquery-ui-lightness.css
 
 if ENABLE_FEEDBACK
-LOLEAFLET_CSS_LST += $(srcdir)/css/iframedialog.css
+COOL_CSS_LST += $(srcdir)/css/iframedialog.css
 endif
 
-LOLEAFLET_CSS = $(filter %,$(LOLEAFLET_CSS_LST))
+COOL_CSS = $(filter %,$(COOL_CSS_LST))
 
-LOLEAFLET_CSS_DST = $(foreach file,$(LOLEAFLET_CSS),$(DIST_FOLDER)/$(notdir $(file)))
-LOLEAFLET_CSS_M4 = $(strip $(foreach file,$(LOLEAFLET_CSS),$(notdir $(file))))
+COOL_CSS_DST = $(foreach file,$(COOL_CSS),$(DIST_FOLDER)/$(notdir $(file)))
+COOL_CSS_M4 = $(strip $(foreach file,$(COOL_CSS),$(notdir $(file))))
 
-$(eval $(call file_targets,$(LOLEAFLET_CSS)))
+$(eval $(call file_targets,$(COOL_CSS)))
 
 NODE_MODULES_JS =\
 	$(if $(IS_SEPARATE),node_modules/hammerjs/hammer.js,node_modules/hammerjs/hammer.min.js) \
@@ -164,7 +164,7 @@ NODE_MODULES_JS =\
 	node_modules/jquery-ui-dist/jquery-ui.js \
 	node_modules/smartmenus/dist/jquery.smartmenus.js
 
-LOLEAFLET_LIBS_JS =\
+COOL_LIBS_JS =\
 	ResizeObserverPolyfill.js \
 	Autolinker.js \
 	json2.js \
@@ -173,24 +173,24 @@ LOLEAFLET_LIBS_JS =\
 	sanitize-url.js
 
 if !ENABLE_MOBILEAPP
-LOLEAFLET_LIBS_JS +=\
+COOL_LIBS_JS +=\
 	l10n.js
 endif
 
-LOLEAFLET_LIBS_JS +=\
+COOL_LIBS_JS +=\
 	w2ui-1.5.rc1.js \
 	viamapi-client.js
 
 NODE_MODULES_JS_SRC = $(patsubst %.js,$(builddir)/%.js,$(NODE_MODULES_JS))
 NODE_MODULES_JS_DST = $(patsubst %.js,$(DIST_FOLDER)/%.js,$(NODE_MODULES_JS))
 
-LOLEAFLET_LIBS_JS_SRC = $(patsubst %.js,$(srcdir)/js/%.js,$(LOLEAFLET_LIBS_JS))
-LOLEAFLET_LIBS_JS_DST = $(patsubst %.js,$(DIST_FOLDER)/%.js,$(LOLEAFLET_LIBS_JS))
+COOL_LIBS_JS_SRC = $(patsubst %.js,$(srcdir)/js/%.js,$(COOL_LIBS_JS))
+COOL_LIBS_JS_DST = $(patsubst %.js,$(DIST_FOLDER)/%.js,$(COOL_LIBS_JS))
 
 # the ordering of this is delicate to get JS initialization right,
 # this list includes both Javascript and Typescript generated files
 # in a rather precise order.
-LOLEAFLET_JS_LST =\
+COOL_JS_LST =\
 	src/Leaflet.js \
 	src/errormessages.js \
 	src/unocommands.js \
@@ -361,29 +361,29 @@ LOLEAFLET_JS_LST =\
 	src/layer/marker/DivOverlay.js
 
 if ENABLE_FEEDBACK
-LOLEAFLET_JS_LST +=\
+COOL_JS_LST +=\
 	src/control/IFrameDialog.js \
 	src/map/handler/Map.Feedback.js
 endif
 
-LOLEAFLET_JS_LST +=\
+COOL_JS_LST +=\
 	src/main.js
 
-LOLEAFLET_JS_WEBORDER = $(filter %,$(LOLEAFLET_JS_LST))
+COOL_JS_WEBORDER = $(filter %,$(COOL_JS_LST))
 
-LOLEAFLET_JS_SRC = $(filter %.js,$(LOLEAFLET_JS_WEBORDER))
-LOLEAFLET_TS_SRC = $(filter %.ts,$(LOLEAFLET_JS_WEBORDER))
+COOL_JS_SRC = $(filter %.js,$(COOL_JS_WEBORDER))
+COOL_TS_SRC = $(filter %.ts,$(COOL_JS_WEBORDER))
 
 # beware these are not helpfully ordered
-LOLEAFLET_TS_JS_DST = $(patsubst src/%.ts,$(DIST_FOLDER)/src/%.js,$(LOLEAFLET_TS_SRC))
-LOLEAFLET_JS_DST = $(patsubst src/%.js,$(DIST_FOLDER)/src/%.js,$(LOLEAFLET_JS_SRC)) $(LOLEAFLET_TS_JS_DST)
+COOL_TS_JS_DST = $(patsubst src/%.ts,$(DIST_FOLDER)/src/%.js,$(COOL_TS_SRC))
+COOL_JS_DST = $(patsubst src/%.js,$(DIST_FOLDER)/src/%.js,$(COOL_JS_SRC)) $(COOL_TS_JS_DST)
 # should be no lingering / obsolete files:
-LOLEAFLET_ASSERT_INTERSECT = $(filter $(LOLEAFLET_JS_SRC), $(patsubst %.ts,%.js,$(LOLEAFLET_TS_SRC)))
+COOL_ASSERT_INTERSECT = $(filter $(COOL_JS_SRC), $(patsubst %.ts,%.js,$(COOL_TS_SRC)))
 
 COMMA := ,
 EMPTY :=
 SPACE := $(EMPTY) $(EMPTY)
-LOLEAFLET_VERSION = $(shell cd $(srcdir) && git log -1 --pretty=format:"%h")
+COOL_VERSION = $(shell cd $(srcdir) && git log -1 --pretty=format:"%h")
 INTERMEDIATE_DIR ?= $(if $(IS_SEPARATE),$(abs_builddir)/debug,$(abs_builddir)/release)
 
 EXTRA_DIST = $(shell find . -type f -not -path './.git/*' -not -path './node_modules/*' | sed 's/.\///')
@@ -395,25 +395,25 @@ define bundle_loleaflet
 			-DGTKAPP=$(ENABLE_GTKAPP) \
 			-DANDROIDAPP=$(ENABLE_ANDROIDAPP) \
 			-DMOBILEAPPNAME="$(APP_NAME)" \
-			-DVERSION=$(LOLEAFLET_VERSION) \
+			-DVERSION=$(COOL_VERSION) \
 			-DCOPYRIGHT=$(srcdir)/src/copyright.js \
-			-DLOLEAFLET_JS=$(subst $(SPACE),$(COMMA),$(patsubst src/%.ts,$(DIST_FOLDER)/src/%.js,$(LOLEAFLET_JS_WEBORDER))) \
+			-DCOOL_JS=$(subst $(SPACE),$(COMMA),$(patsubst src/%.ts,$(DIST_FOLDER)/src/%.js,$(COOL_JS_WEBORDER))) \
 			$(srcdir)/loleaflet-src.js.m4 > $@)
 endef
 
 define prereq_loleaflet
-	$(if $(IS_SEPARATE),$(LOLEAFLET_JS_DST),$(LOLEAFLET_JS_SRC))
+	$(if $(IS_SEPARATE),$(COOL_JS_DST),$(COOL_JS_SRC))
 endef
 
 define bundle_css
 	$(if $(IS_SEPARATE),\
 		@touch $@,\
 		@echo "Uglify loleaflet css files..."
-		@$(NODE) node_modules/uglifycss/uglifycss $(LOLEAFLET_CSS) > $@)
+		@$(NODE) node_modules/uglifycss/uglifycss $(COOL_CSS) > $@)
 endef
 
 define prereq_css
-	$(if $(IS_SEPARATE),$(LOLEAFLET_CSS_DST),$(LOLEAFLET_CSS))
+	$(if $(IS_SEPARATE),$(COOL_CSS_DST),$(COOL_CSS))
 endef
 
 define bundle_all
@@ -422,8 +422,8 @@ define bundle_all
 		@echo "Uglify loleaflet js files..."
 		@m4 -PE -DL10N_IOS_ALL_JS=$(L10N_IOS_ALL_JS) \
 			-DNODE_MODULES_JS=$(subst $(SPACE),$(COMMA),$(NODE_MODULES_JS)) \
-			-DLOLEAFLET_LIBS_JS=$(subst $(SPACE),$(COMMA),$(LOLEAFLET_LIBS_JS_SRC)) \
-			-DLOLEAFLET_JS=$(INTERMEDIATE_DIR)/loleaflet-src.js \
+			-DCOOL_LIBS_JS=$(subst $(SPACE),$(COMMA),$(COOL_LIBS_JS_SRC)) \
+			-DCOOL_JS=$(INTERMEDIATE_DIR)/loleaflet-src.js \
 			$(srcdir)/bundle.js.m4 > $(INTERMEDIATE_DIR)/bundle.js
 		@$(NODE) node_modules/uglify-js/bin/uglifyjs \
 			$(INTERMEDIATE_DIR)/bundle.js \
@@ -431,8 +431,8 @@ define bundle_all
 endef
 
 define prereq_all
-	$(if $(IS_SEPARATE),$(NODE_MODULES_JS_DST) $(LOLEAFLET_LIBS_JS_DST),\
-		$(NODE_MODULES_JS_SRC) $(LOLEAFLET_LIBS_JS_SRC))
+	$(if $(IS_SEPARATE),$(NODE_MODULES_JS_DST) $(COOL_LIBS_JS_DST),\
+		$(NODE_MODULES_JS_SRC) $(COOL_LIBS_JS_SRC))
 endef
 
 define global_file
@@ -455,11 +455,11 @@ $(TYPESCRIPT_JS_DIR)/%.js: $(srcdir)/%.ts
 	$(builddir)/node_modules/typescript/bin/tsc --outFile $@ $<
 
 build-loleaflet: \
-	$(LOLEAFLET_L10N_DST) \
+	$(COOL_L10N_DST) \
 	$(L10N_JSON) \
 	$(SRC_TS_JS_DST) \
-	$(LOLEAFLET_IMAGES_DST) \
-	$(LOLEAFLET_IMAGES_CUSTOM_DST) \
+	$(COOL_IMAGES_DST) \
+	$(COOL_IMAGES_CUSTOM_DST) \
 	$(JQUERY_LIGHTNESS_DIST_IMAGES) \
 	$(JQUERY_MINIFIED_DIST_IMAGES) \
 	$(ADMIN_BUNDLE) \
@@ -483,21 +483,21 @@ if ENABLE_CYPRESS
 	@echo "Added HTML file for multiuser tests"
 endif
 
-$(DIST_FOLDER)/admin-bundle.js: $(LOLEAFLET_ADMIN_DST) \
+$(DIST_FOLDER)/admin-bundle.js: $(COOL_ADMIN_DST) \
 	$(INTERMEDIATE_DIR)/admin-src.js
 	@NODE_PATH=$(abs_builddir)/node_modules:$(INTERMEDIATE_DIR) $(NODE) node_modules/browserify/bin/cmd.js -g browserify-css $(if $(IS_SEPARATE),--debug,-g uglifyify) -o $@ $(srcdir)/admin/main-admin.js
 
-$(INTERMEDIATE_DIR)/admin-src.js: $(LOLEAFLET_ADMIN_TS_JS) $(LOLEAFLET_ADMIN_JS)
+$(INTERMEDIATE_DIR)/admin-src.js: $(COOL_ADMIN_TS_JS) $(COOL_ADMIN_JS)
 	@mkdir -p $(dir $@)
 	@echo "Checking for admin JS errors..."
 	@$(NODE) node_modules/eslint/bin/eslint.js --resolve-plugins-relative-to $(abs_builddir) --ignore-path $(srcdir)/.eslintignore --config $(srcdir)/.eslintrc --no-eslintrc $(srcdir)/admin/src
-	@awk 'FNR == 1 {print ""} 1' $(LOLEAFLET_ADMIN_TS_JS) $(patsubst %.js,$(srcdir)/%.js,$(LOLEAFLET_ADMIN_JS)) > $@
+	@awk 'FNR == 1 {print ""} 1' $(COOL_ADMIN_TS_JS) $(patsubst %.js,$(srcdir)/%.js,$(COOL_ADMIN_JS)) > $@
 
-$(INTERMEDIATE_DIR)/loleaflet-src.js: tscompile.done $(call prereq_loleaflet) $(LOLEAFLET_JS_DST)
+$(INTERMEDIATE_DIR)/loleaflet-src.js: tscompile.done $(call prereq_loleaflet) $(COOL_JS_DST)
 	@mkdir -p $(dir $@)
 	$(abs_top_srcdir)/scripts/unocommands.py --check $(abs_top_srcdir)
 	@printf "Checking for obsolete JS build intermediates in this makefile... "
-	@if ! test "z$(LOLEAFLET_ASSERT_INTERSECT)" == "z"; then echo; echo "Error: please remove obsolete files:"; echo "$(LOLEAFLET_ASSERT_INTERSECT)"; exit 1; else echo "clean"; fi
+	@if ! test "z$(COOL_ASSERT_INTERSECT)" == "z"; then echo; echo "Error: please remove obsolete files:"; echo "$(COOL_ASSERT_INTERSECT)"; exit 1; else echo "clean"; fi
 	@echo "Checking for loleaflet JS errors..."
 	@$(NODE) node_modules/eslint/bin/eslint.js $(srcdir)/src --resolve-plugins-relative-to $(abs_builddir) \
 		$(srcdir)/js --ignore-path $(srcdir)/.eslintignore --no-eslintrc --config $(srcdir)/.eslintrc
@@ -519,8 +519,8 @@ $(DIST_FOLDER)/global.js: $(srcdir)/js/global.js
 	$(call global_file)
 
 $(DIST_FOLDER)/cool.html: $(srcdir)/html/cool.html.m4 \
-	$(LOLEAFLET_HTML_DST) \
-	$(LOLEAFLET_WELCOME_DST) \
+	$(COOL_HTML_DST) \
+	$(COOL_WELCOME_DST) \
 	$(DIST_FOLDER)/bundle.css \
 	$(DIST_FOLDER)/global.js \
 	$(DIST_FOLDER)/bundle.js
@@ -531,11 +531,11 @@ $(DIST_FOLDER)/cool.html: $(srcdir)/html/cool.html.m4 \
 		-DGTKAPP=$(ENABLE_GTKAPP) \
 		-DANDROIDAPP=$(ENABLE_ANDROIDAPP) \
 		-DMOBILEAPPNAME="$(APP_NAME)" \
-		-DLOLEAFLET_CSS="$(subst $(SPACE),$(COMMA),$(LOLEAFLET_CSS_M4))" \
+		-DCOOL_CSS="$(subst $(SPACE),$(COMMA),$(COOL_CSS_M4))" \
 		-DGLOBAL_JS="$(DIST_FOLDER)/global.js" \
-		-DLOLEAFLET_JS="$(subst $(SPACE),$(COMMA),$(NODE_MODULES_JS) \
-		$(LOLEAFLET_LIBS_JS) \
-		$(patsubst %.ts,%.js,$(LOLEAFLET_JS_WEBORDER)))" \
+		-DCOOL_JS="$(subst $(SPACE),$(COMMA),$(NODE_MODULES_JS) \
+		$(COOL_LIBS_JS) \
+		$(patsubst %.ts,%.js,$(COOL_JS_WEBORDER)))" \
 		-DVENDOR="$(VENDOR)" \
 		$(srcdir)/html/cool.html.m4 > $@
 
@@ -583,11 +583,11 @@ $(DIST_FOLDER)/welcome/%.html: $(srcdir)/welcome/%.html
 		`ln -sf $(abs_srcdir)/$< $@`; \
 	fi
 
-tscompile.done: $(LOLEAFLET_JS_SRC) $(LOLEAFLET_TS_SRC)
+tscompile.done: $(COOL_JS_SRC) $(COOL_TS_SRC)
 	$(builddir)/node_modules/typescript/bin/tsc --typeRoots $(builddir)/node_modules/@types --outDir $(DIST_FOLDER)/src --rootDir $(srcdir)/src --checkJs false --project $(srcdir)/tsconfig.json
 	@touch $@
 
-$(LOLEAFLET_TS_JS_DST): tscompile.done
+$(COOL_TS_JS_DST): tscompile.done
 	@:
 
 $(DIST_FOLDER)/src/%.js: $(srcdir)/src/%.js
@@ -716,7 +716,7 @@ clean-local:
 CLEANFILES = tscompile.done $(INTERMEDIATE_DIR)/loleaflet-src.js $(DIST_FOLDER)/bundle.css $(DIST_FOLDER)/bundle.js $(INTERMEDIATE_DIR)/loleaflet-src.js
 
 ctags:
-	@$(CTAGS) --language-force=JavaScript $(LOLEAFLET_JS_SRC) $(srcdir)/js/global.js
+	@$(CTAGS) --language-force=JavaScript $(COOL_JS_SRC) $(srcdir)/js/global.js
 
 $(abs_srcdir)/jsconfig.json:
 	@printf "{\n \
